package view;

import controller.ControladorFrmPasswordOlvidada;
import controller.SistemaAutenticacion;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;

public class FrmPasswordOlvidada extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmPasswordOlvidada.class.getName());

    private JTextField txtCorreo;
    private JButton btnEnviar;
    private JButton btnCancelar;
    private ControladorFrmPasswordOlvidada controlador;

    public FrmPasswordOlvidada(SistemaAutenticacion sistemaAuth) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        configurarVista();
        setLocationRelativeTo(null);
        controlador = new ControladorFrmPasswordOlvidada(this, sistemaAuth);
    }

    private void configurarVista() {
        setTitle("Recuperar contraseña");
        setResizable(false);

        JPanel panelPrincipal = new JPanel();
        panelPrincipal.setBackground(Color.WHITE);
        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        java.awt.GridBagConstraints gbc = new java.awt.GridBagConstraints();
        gbc.insets = new java.awt.Insets(10, 20, 5, 20);
        gbc.fill = java.awt.GridBagConstraints.HORIZONTAL;

        JLabel lblTitulo = new JLabel("Recuperar contraseña");
        lblTitulo.setFont(new Font("Tw Cen MT", Font.BOLD, 22));
        lblTitulo.setForeground(new Color(18, 18, 18));
        gbc.gridx = 0; gbc.gridy = 0; gbc.gridwidth = 2;
        panelPrincipal.add(lblTitulo, gbc);

        JLabel lblSubtitulo = new JLabel("Ingrese su correo para recibir el código de verificación.");
        lblSubtitulo.setFont(new Font("Tw Cen MT", Font.PLAIN, 13));
        lblSubtitulo.setForeground(new Color(100, 100, 100));
        gbc.gridy = 1;
        panelPrincipal.add(lblSubtitulo, gbc);

        JLabel lblCorreo = new JLabel("Correo electrónico");
        lblCorreo.setFont(new Font("Tw Cen MT", Font.BOLD, 15));
        gbc.gridy = 2; gbc.gridwidth = 2; gbc.insets = new java.awt.Insets(20, 20, 2, 20);
        panelPrincipal.add(lblCorreo, gbc);

        txtCorreo = new JTextField();
        txtCorreo.setFont(new Font("Tw Cen MT", Font.PLAIN, 14));
        txtCorreo.setBorder(BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(200, 200, 200)));
        txtCorreo.setPreferredSize(new java.awt.Dimension(340, 30));
        gbc.gridy = 3; gbc.insets = new java.awt.Insets(0, 20, 15, 20);
        panelPrincipal.add(txtCorreo, gbc);

        JPanel panelBotones = new JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 10, 0));
        panelBotones.setBackground(Color.WHITE);

        btnEnviar = new JButton("Enviar código");
        btnEnviar.setFont(new Font("Tw Cen MT", Font.BOLD, 14));
        btnEnviar.setBackground(new Color(253, 155, 170));
        btnEnviar.setForeground(new Color(51, 51, 51));
        btnEnviar.setBorderPainted(false);
        btnEnviar.setPreferredSize(new java.awt.Dimension(150, 38));
        btnEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) { btnEnviar.setBackground(Color.PINK); }
            public void mouseExited(java.awt.event.MouseEvent evt) { btnEnviar.setBackground(new Color(253, 155, 170)); }
        });
        btnEnviar.addActionListener(e -> controlador.manejarEnvioCorreo());

        btnCancelar = new JButton("Cancelar");
        btnCancelar.setFont(new Font("Tw Cen MT", Font.PLAIN, 14));
        btnCancelar.setBackground(new Color(230, 230, 230));
        btnCancelar.setForeground(new Color(51, 51, 51));
        btnCancelar.setBorderPainted(false);
        btnCancelar.setPreferredSize(new java.awt.Dimension(100, 38));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addActionListener(e -> controlador.manejarCancelar());

        panelBotones.add(btnEnviar);
        panelBotones.add(btnCancelar);

        gbc.gridy = 4; gbc.insets = new java.awt.Insets(5, 20, 20, 20);
        panelPrincipal.add(panelBotones, gbc);

        getContentPane().removeAll();
        getContentPane().add(panelPrincipal);
        pack();
    }

    public String getCorreoIngresado() {
        return txtCorreo.getText().trim();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmPasswordOlvidada(new controller.SistemaAutenticacion()).setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
